# Tutorial for Julia Basic
#### Adapted from Michael O'Niell, UNC Chapel Hill STOR 415

this is just text $c = \sqrt{a^2+b^2}$. on its own line:
$$
E=mc^2
$$
you can also do lists:
- first
- second
- third
and that's it. Here is a [link to google](https://www.google.com)

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | \$1600 |
| col 2 is      | centered      |   \$12 |
| zebra stripes | are neat      |    \$1 |

In [1]:
#=
this is a comment
that spans multiple lines
=#
x=2+3
y=1+1;

println("the answer is: ", x+y)

the answer is: 7


Julia can also use unicode symbols. Type \pi and press tab to create the pi character.

In [2]:
2π

6.283185307179586

Other symbols can be defined as variables as well. For example, typing \turtle and tab gives:

In [3]:
🐢 = 5

5

In [4]:
🐢^2

25

Generally speaking, I would not suggest using symbols in code. However, some Julia code will use symbols (such as greek letters), so it is good to understand how it works.

Julia also natively supports vectors and matrices:

In [5]:
x = [1 2 3]
# row vector

1×3 Matrix{Int64}:
 1  2  3

In [7]:
y = [1, 2, 3]
# column vector 

3-element Vector{Int64}:
 1
 2
 3

In [8]:
x*y
# inner product, vector multiplication

1-element Vector{Int64}:
 14

In [9]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [10]:
A = []

Any[]

In [11]:
# adds to initialized list 'A'
push!(A, "hello")

1-element Vector{Any}:
 "hello"

In [12]:
push!(A, rand(2,3))

2-element Vector{Any}:
 "hello"
 [0.9619618438295903 0.2368097682207988 0.7196583287570343; 0.011762873642143123 0.739052910846281 0.5944276914211861]

In [13]:
push!(A, A)

3-element Vector{Any}:
 "hello"
 [0.9619618438295903 0.2368097682207988 0.7196583287570343; 0.011762873642143123 0.739052910846281 0.5944276914211861]
 3-element Vector{Any}:#= circular reference @-1 =#

We can also create arrays using the range functionality:

In [24]:
x = 1:5
y = 10:-2:0

for i in x
    print(i, " ")
    print("hello ")
end
println("")
for j in y
    print(j, " ")
end

1 hello 2 hello 3 hello 4 hello 5 hello 
10 8 6 4 2 0 

We can use this functionality to make writing loops easier.

In [15]:
x = [3 4 5 6 7]
for i in 1:4
    println(x[i]*x[i+1])
end

12
20
30
42


We can generate vectors of uniformly random variables with:

In [16]:
x = rand(5)

5-element Vector{Float64}:
 0.30705423743972315
 0.9240944998885128
 0.5047167652787525
 0.9233469643150372
 0.004005026790086297

In [17]:
for i in 3:5
    println(x[i])
end

0.5047167652787525
0.9233469643150372
0.004005026790086297


There are some special vectors in Julia.

In [18]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [19]:
y = zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

We can also create the identity matrix using these vectors with the LinearAlgebra package.

In [22]:
#If you have not used LinearAlgebra before, call
using Pkg
Pkg.add("LinearAlgebra")

using LinearAlgebra
I = diagm(ones(3))

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed FFMPEG_jll ─ v4.4.2+2
    Updating `~/.julia/environments/v1.7/Project.toml`
  [37e2e46d] + LinearAlgebra
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [b22a6f82] ↑ FFMPEG_jll v4.4.2+0 ⇒ v4.4.2+2
  [efcefdf7] + PCRE2_jll
Precompiling project...
  ✓ PCRE2_jll
  ✓ FFMPEG_jll
  ✗ FFMPEG
  ✗ GR_jll
  2 dependencies successfully precompiled in 11 seconds (162 already precompiled)
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages


3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

Copying vectors in Julia requires using the copy command, using = only makes a reference to the same vector. See the below example:

In [90]:
x

5-element Array{Float64,1}:
 0.148972
 0.42514 
 0.591444
 0.624182
 0.703856

In [41]:
y = x

5-element Array{Float64,1}:
 0.309248
 0.351407
 0.472381
 0.506109
 0.634877

In [42]:
y

5-element Array{Float64,1}:
 0.309248
 0.351407
 0.472381
 0.506109
 0.634877

In [43]:
x[1] = 2

2

In [44]:
x

5-element Array{Float64,1}:
 2.0     
 0.351407
 0.472381
 0.506109
 0.634877

In [45]:
y

5-element Array{Float64,1}:
 2.0     
 0.351407
 0.472381
 0.506109
 0.634877

In [46]:
z = copy(x)

5-element Array{Float64,1}:
 2.0     
 0.351407
 0.472381
 0.506109
 0.634877

In [47]:
x[2] = 6

6

In [48]:
x

5-element Array{Float64,1}:
 2.0     
 6.0     
 0.472381
 0.506109
 0.634877

In [49]:
y

5-element Array{Float64,1}:
 2.0     
 6.0     
 0.472381
 0.506109
 0.634877

In [50]:
z

5-element Array{Float64,1}:
 2.0     
 0.351407
 0.472381
 0.506109
 0.634877

Another useful type of data structure in Julia is dictionaries. Dictionaries map a key to a value. For example:

In [27]:
mydictionary = Dict([("A",1),("B",2)])
mydictionary["B"]

2

We can also add elements to our dictionary over time.

In [26]:
mydictionary["C"] = 3
for (key, value) in mydictionary
    println("key = ", key, " value = ", value)
end

LoadError: UndefVarError: mydictionary not defined

Plotting is also relatively easy in Julia.

In [34]:
#If you haven't used Plots before, run
using Pkg
Pkg.add("Plots")
using Plots
Pkg.update("Plots")

x = LinRange(0,2π, 100)
#broadcast by coordinate 
y = sin.(x)
plot(x,y,linestyle=:dash,linecolor=:red,linewidth=3)

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1423
ERROR: LoadError: InitError: could not load library "/Users/caitlinlewis/.julia/artifacts/1e28bb4254c27b51008f9e1839edee3406036044/lib/libavdevice.58.13.100.dylib"
dlopen(/Users/caitlinlewis/.julia/artifacts/1e28bb4254c27b51008f9e1839edee3406036044/lib/libavdevice.58.13.100.dylib, 1): Library not loaded: @rpath/libglib-2.0.0.dylib
  Referenced from: /Users/caitlinlewis/.julia/artifacts/1e28bb4254c27b51008f9e1839edee3406036044/lib/libavdevice.58.13.100.dylib
  Reason: Incompatible library version: libavdevice.58.13.100.dylib requires version 7401.0.0 or later, but libglib-2.0.0.dylib provides version 6801.0.0
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt3

LoadError: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /Users/caitlinlewis/.julia/compiled/v1.7/Plots/jl_eDOrUS.

We can also do fancier plotting.

In [28]:
#Example from https://docs.juliaplots.org/stable/
# define the Lorenz attractor
Base.@kwdef mutable struct Lorenz
    dt::Float64 = 0.02
    σ::Float64 = 10
    ρ::Float64 = 28
    β::Float64 = 8/3
    x::Float64 = 1
    y::Float64 = 1
    z::Float64 = 1
end

function step!(l::Lorenz)
    dx = l.σ * (l.y - l.x)
    dy = l.x * (l.ρ - l.z) - l.y
    dz = l.x * l.y - l.β * l.z
    l.x += l.dt * dx
    l.y += l.dt * dy
    l.z += l.dt * dz
end

attractor = Lorenz()


# initialize a 3D plot with 1 empty series
plt = plot3d(
    1,
    xlim = (-30, 30),
    ylim = (-30, 30),
    zlim = (0, 60),
    title = "Lorenz Attractor",
    marker = 2,
)

# build an animated gif by pushing new points to the plot, saving every 10th frame
@gif for i=1:1500
    step!(attractor)
    push!(plt, attractor.x, attractor.y, attractor.z)
end every 10


LoadError: UndefVarError: plot3d not defined